<?php
function feeds_content_rewriter_feeds_after_parse($source, $result) {
    $form_state_values = variable_get('feeds_content_rewriter_form_state_values', array());

    dsm($form_state_values['stopwords']);
    dsm(is_array($form_state_values['stopwords']));

    if($form_state_values['rewrite_content'] == TRUE) {
        if(!empty($form_state_values['stopwords'])) {
            $stopwords = explode("\n", $form_state_values['stopwords']);
        }
        else {
            $stopwords = NULL;
        }

        if(!empty($form_state_values['ignored_words'])) {
            $ignored_words = explode("\n", $form_state_values['ignored_words']);
        }
        else {
            $ignored_words = NULL;
        }

        if($form_state_values['stopwords_only'] && !$form_state_values['spintax_output']) {
            foreach($result -> items as $key => $item) {
                $result -> items[$key]['description'] = mb_string_convert($item['description'], $stopwords, $ignored_words);
            }
        }
        else if($form_state_values['spintax_output']) {
            foreach($result -> items as $key => $item) {
                $spun_string = spin_string($item['description'], 1);

                if(is_array($spun_string)) {
                    $result -> items[$key]['description'] = implode("", $spun_string);
                }
            }

            if($form_state_values['rewrite_after_spin'] && !$form_state_values['stopwords_only']) {
                foreach($result -> items as $key => $item) {
                    $result -> items[$key]['description'] = mb_string_convert($item['description'], NULL, $ignored_words);
                }
            }
            else if($form_state_values['rewrite_after_spin'] && $form_state_values['stopwords_only']) {
                foreach($result -> items as $key => $item) {
                    $result -> items[$key]['description'] = mb_string_convert($item['description'], $stopwords, $ignored_words);
                }
            }
        }
        else if(!$form_state_values['stopwords_only'] && !$form_state_values['spintax_output']) {
            foreach($result -> items as $key => $item) {
                $result -> items[$key]['description'] = mb_string_convert($item['description'], NULL, $ignored_words);
            }
        }
    }
}

function feeds_content_rewriter_form_alter(&$form, &$form_state, $form_id) {
    if($form_id == 'feed_node_form') {
        $form['content_rewriter'] = array (
            '#type' => 'fieldset',
            '#title' => 'Content Rewriter',
            '#collapsible' => TRUE,
            '#collapsed' => TRUE,
            '#weight' => 100,
            '#group' => 'additional_settings'
        );

        $form['content_rewriter']['rewrite_content'] = array (
            '#type' => 'checkbox',
            '#title' => 'Rewrite Content'
        );

        $form['content_rewriter']['stopwords'] = array (
            '#type' => 'textarea',
            '#title' => 'Stopwords',
            '#description' => 'Enter words that you would like rewritten.',
            '#resizeable' => TRUE
        );

        $form['content_rewriter']['ignored_words'] = array (
            '#type' => 'textarea',
            '#title' => 'Ignored Words',
            '#description' => 'Enter words that you would not want rewritten.',
            '#resizeable' => TRUE
        );

        $form['content_rewriter']['stopwords_only'] = array (
            '#type' => 'checkbox',
            '#title' => 'Stopwords Only'
        );

        $form['content_rewriter']['spintax_output'] = array (
            '#type' => 'checkbox',
            '#title' => 'Spintax Output'
        );

        $form['content_rewriter']['rewrite_after_spin'] = array (
            '#type' => 'checkbox',
            '#title' => 'Rewrite After Spinning'
        );

        $form['#validate'][] = 'feeds_content_rewriter_form_validate';
        $form['#submit'][] = 'feeds_content_rewriter_form_submit';
    }
}

function feeds_content_rewriter_feeds_after_import($source) {
    variable_del('feeds_content_rewriter_form_state_values');
}

function feeds_content_rewriter_form_validate($form, &$form_state) {
    $form_state_values = $form_state['values'];
    if($form_state_values['rewrite_content'] == TRUE) {
        if($form_state_values['stopwords_only'] && $form_state_values['spintax_output'] && !$form_state_values['rewrite_after_spin']) {
            form_set_error('rewrite_after_spin', 'Please check the rewrite after spin checkbox if you want to rewrite on stopwords.');
        }

        if(!$form_state_values['spintax_output'] && $form_state_values['rewrite_after_spin']) {
           form_set_error('rewrite_after_spin', 'Please check the spintax output checkbox if you want to rewrite after spinning content.');
        }

        if($form_state_values['stopwords_only'] && empty($form_state_values['stopwords'])) {
            form_set_error('stopwords', 'Stopwords checked, but no stopwords exist.');
        }
    }
}

function feeds_content_rewriter_form_submit($form, &$form_state) {
    variable_set('feeds_content_rewriter_form_state_values', $form_state['values']);
}